// Catalog data context: fetched once at boot from ./catalog.json (a static file generated by
// scripts/build-catalog.mjs and served from public/). No other data source exists at runtime.

import { createContext, useContext, useEffect, useState, type ReactNode } from "react";
import type { Catalog, Plugin } from "./types";

interface CatalogState {
  catalog: Catalog | null;
  error: string | null;
}

const CatalogContext = createContext<CatalogState>({ catalog: null, error: null });

export function CatalogProvider({ children }: { children: ReactNode }) {
  const [state, setState] = useState<CatalogState>({ catalog: null, error: null });

  useEffect(() => {
    let cancelled = false;
    fetch("catalog.json", { cache: "no-cache" })
      .then((r) => {
        if (!r.ok) throw new Error("HTTP " + r.status);
        return r.json() as Promise<Catalog>;
      })
      .then((catalog) => {
        if (!cancelled) setState({ catalog, error: null });
      })
      .catch((err: Error) => {
        if (!cancelled) setState({ catalog: null, error: err.message });
      });
    return () => {
      cancelled = true;
    };
  }, []);

  return <CatalogContext.Provider value={state}>{children}</CatalogContext.Provider>;
}

export function useCatalog(): CatalogState {
  return useContext(CatalogContext);
}

export function usePlugin(name: string | undefined): Plugin | undefined {
  const { catalog } = useCatalog();
  if (!catalog || !name) return undefined;
  return catalog.plugins.find((p) => p.name === name);
}

export function installCommandFor(catalog: Catalog, pluginName: string): string {
  return catalog.marketplace.installTemplate.replace("{plugin}", pluginName);
}
