// Shapes of site/public/catalog.json (generated by scripts/build-catalog.mjs — see docs/SITE-SPEC.md).

export interface Owner {
  name: string;
  email: string;
}

export interface MarketplaceInfo {
  name: string;
  displayName: string;
  description: string;
  owner: Owner;
  repository: string;
  repoShort: string;
  addCommand: string;
  installTemplate: string;
}

export interface SkillEntry {
  name: string;
  description: string;
}

export interface AgentEntry {
  name: string;
  description: string;
  model: string | null;
}

export interface CommandEntry {
  name: string;
  description: string;
}

export interface DependencyRef {
  name: string;
  version?: string;
}

export interface Plugin {
  name: string;
  displayName: string;
  version: string;
  description: string;
  category: string;
  keywords: string[];
  author: Owner | null;
  license: string | null;
  repository: string | null;
  dependencies: DependencyRef[];
  skills: SkillEntry[];
  agents: AgentEntry[];
  commands: CommandEntry[];
  hookEvents: string[];
}

export interface Catalog {
  schemaVersion: number;
  generatedAt: string;
  marketplace: MarketplaceInfo;
  plugins: Plugin[];
}
